fieldLayouts:
  a166a969-388c-4d6b-a789-f0391b906dcd:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 931de94d-cb1a-4e39-bab5-17182d8720a7 # Asset Alt Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: services
hasUrls: true
name: Services
settings:
  path: ./uploads/services
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\volumes\Local
url: ./uploads/services
