fieldLayouts:
  b568227e-a052-44db-8758-26e2adb4d77a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 3beb3ad3-b5cd-4773-a3f6-8fd64f9bf2c4 # Data Privacy Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: dataPrivacy
hasTitleField: false
name: 'Data Privacy'
section: 1710e260-6d3a-4ad9-9f43-4a26382e3fb9 # Data Privacy
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
