fieldLayouts:
  a08e08f2-1695-4fa1-968d-b54c2c2c0c6f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 440135a1-bac2-4911-b82f-f00f8edf72ea # References Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Preview
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4de8ced8-785b-4cf8-8964-04f7960b6886 # References Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3e5a5869-5639-4dee-b10c-120697405c15 # References Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 16610df2-605b-441e-893f-4c0b82054b7c # References Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e0300dda-fbec-4fb1-96d8-82e87cbadf1e # References Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a4ce92ad-1904-4896-9957-ba44baa59842 # References Cooperations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Detail
        sortOrder: 2
handle: references
hasTitleField: true
name: References
section: 87da02c3-db0c-443c-bdd7-da8e5a97ed6d # References
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
