fieldLayouts:
  a08e08f2-1695-4fa1-968d-b54c2c2c0c6f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 440135a1-bac2-4911-b82f-f00f8edf72ea # Project Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fc61f991-01d9-4f7d-807e-fcf2fd5a9609 # Project Preview Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Preview
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c4ddc7de-3e21-4e79-a6a9-c0666c4159be # Project Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4de8ced8-785b-4cf8-8964-04f7960b6886 # Project Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 16610df2-605b-441e-893f-4c0b82054b7c # Project Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e0300dda-fbec-4fb1-96d8-82e87cbadf1e # Project Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a4ce92ad-1904-4896-9957-ba44baa59842 # Project Cooperations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8a0010c-760c-420d-8f7b-8a571d116685 # Project Next
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4272ad3a-ba0a-4411-a3ff-ad06cfea004e # Project Employee Relationship
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Detail
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 210c2e23-d00b-41f3-8b82-f54da7597837 # Project Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Overview
        sortOrder: 3
handle: references
hasTitleField: false
name: References
section: 87da02c3-db0c-443c-bdd7-da8e5a97ed6d # Projects
sortOrder: 1
titleFormat: '{{ parent.title }} ({{ projectHeading }})'
titleTranslationKeyFormat: null
titleTranslationMethod: site
