name: Gravity Link
preview: "@dark"
context: 
  content: Gravity Link
  href: '#'
  color: white
variants:
  - name: small
    context:
      content: Gravity Link (small)
      style: small
  - name: serif
    context:
      content: Gravity Link (serif)
      style: serif