name: Gravity Link
preview: "@dark"
context: 
  content: Link
  href: '#'
  color: white
variants:
  - name: small
    context:
      content: Link (small)
      style: small
  - name: serif
    context:
      content: Link (serif)
      style: serif