field: 5ad7b01a-68e1-4dfe-9df3-e9ffca1de7f5 # Imprint Box
fieldLayouts:
  76920208-e8d4-4e18-b354-10e5a0921d7f:
    tabs:
      -
        elements:
          -
            fieldUid: 58f73fe0-0362-4ee7-8383-57cd67040f70 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 953f17ff-a718-42fa-b333-c914a8ab23e4 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  58f73fe0-0362-4ee7-8383-57cd67040f70: # Heading
    columnSuffix: bkbyztgr
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  953f17ff-a718-42fa-b333-c914a8ab23e4: # Text
    columnSuffix: ocsyhggs
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Paragraph.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: box
name: Box
sortOrder: 1
