columnSuffix: qqggvjqt
contentColumnType: text
fieldGroup: 730cd0d2-75f2-4352-afca-85aad702b46f # Asset
handle: assetPhotographer
instructions: ''
name: 'Asset Photographer'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
