columnSuffix: wigmwqsl
contentColumnType: string(20)
fieldGroup: 89a176fa-8575-4f8a-a6e4-e4c34ec8b721 # Contact Details
handle: contactDetailsZip
instructions: ''
name: 'Contact Details ZIP'
searchable: false
settings:
  byteLimit: null
  charLimit: 5
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
