columnSuffix: fzfosvjx
contentColumnType: string(255)
fieldGroup: 89a176fa-8575-4f8a-a6e4-e4c34ec8b721 # Contact Details
handle: contactDetailsLinkedin
instructions: ''
name: 'Contact Details Linkedin'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
