columnSuffix: hpyyytqc
contentColumnType: text
fieldGroup: 16285aca-5a6c-469c-abb4-f13c8cbe8ecd # Footer
handle: footerCopyright
instructions: ''
name: 'Footer Copyright'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
