columnSuffix: null
contentColumnType: string
fieldGroup: 9bbcdb7c-8d5d-4d80-a9ca-37ed98d82ee0 # Hero
handle: heroImages
instructions: ''
name: 'Hero Images'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:8784cdc1-ffc3-4a53-9e0d-333108d8a5d5' # Projects
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:8784cdc1-ffc3-4a53-9e0d-333108d8a5d5' # Projects
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:8784cdc1-ffc3-4a53-9e0d-333108d8a5d5' # Projects
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
