columnSuffix: null
contentColumnType: string
fieldGroup: 03a93c3b-918b-4335-a499-081b17ad9626 # Imprint
handle: imprintBox
instructions: ''
name: 'Imprint Box'
searchable: false
settings:
  contentTable: '{{%matrixcontent_imprintbox}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
