columnSuffix: null
contentColumnType: string
fieldGroup: fbbd889b-3a5c-4d2c-8c31-2f6b6e232329 # Navigation
handle: navigationCta
instructions: ''
name: 'Navigation CTA'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navigationcta}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
