columnSuffix: kwbsaayd
contentColumnType: text
fieldGroup: 458a9587-6610-4f78-9592-5e56e1adfcf9 # Project
handle: projectDate
instructions: ''
name: 'Project Date'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
