columnSuffix: jzlhvpty
contentColumnType: boolean
fieldGroup: 458a9587-6610-4f78-9592-5e56e1adfcf9 # Project
handle: projectEmployeeRelationship
instructions: ''
name: 'Project Employee Relationship'
searchable: false
settings:
  default: false
  offLabel: self-employed
  onLabel: employed
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
