columnSuffix: null
contentColumnType: string
fieldGroup: 458a9587-6610-4f78-9592-5e56e1adfcf9 # References
handle: referencesItems
instructions: ''
name: 'References Items'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:87da02c3-db0c-443c-bdd7-da8e5a97ed6d' # References
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
