columnSuffix: null
contentColumnType: string
fieldGroup: 5365b4bb-47ef-425d-8d42-75f6aba9c7b6 # Service
handle: servicesCategories
instructions: ''
name: 'Services Categories'
searchable: false
settings:
  contentTable: '{{%matrixcontent_servicescategories}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
