columnSuffix: idmiwzzj
contentColumnType: text
fieldGroup: 785c8054-7a1d-49c1-87f5-75de0bc45d9f # Team Member
handle: teamMemberMobile
instructions: ''
name: 'Team Member Mobile'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
