defaultPlacement: end
enableVersioning: true
handle: dataPrivacy
name: 'Data Privacy'
propagationMethod: all
siteSettings:
  1c00b42a-dae4-4f15-a772-533bb5b53e7c: # Lautissimi (DE)
    enabledByDefault: true
    hasUrls: true
    template: 05_pages/p-data-privacy.twig
    uriFormat: legal/data-privacy
type: single
