defaultPlacement: end
enableVersioning: true
handle: intro
name: Intro
propagationMethod: all
siteSettings:
  1c00b42a-dae4-4f15-a772-533bb5b53e7c: # Lautissimi
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
