defaultPlacement: end
enableVersioning: true
handle: newsletter
name: Newsletter
propagationMethod: all
siteSettings:
  1c00b42a-dae4-4f15-a772-533bb5b53e7c: # Lautissimi (DE)
    enabledByDefault: true
    hasUrls: true
    template: 05_pages/p-newsletter.twig
    uriFormat: newsletter
  cbdca878-f920-45ad-9c48-262b21cf7421: # Lautissimi (EN)
    enabledByDefault: true
    hasUrls: true
    template: 05_pages/p-newsletter.twig
    uriFormat: newsletter
type: single
