defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  1c00b42a-dae4-4f15-a772-533bb5b53e7c: # Lautissimi (DE)
    enabledByDefault: true
    hasUrls: true
    template: 'pages/{slug}'
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 15ee700b-e250-4ce6-b411-6bceaa38dfd5
type: structure
