defaultPlacement: end
enableVersioning: true
handle: references
name: References
propagationMethod: all
siteSettings:
  1c00b42a-dae4-4f15-a772-533bb5b53e7c: # Lautissimi
    enabledByDefault: true
    hasUrls: true
    template: refer/_entry
    uriFormat: 'references/{slug}'
structure:
  maxLevels: null
  uid: b70de299-a53e-4e32-a27c-37b158c84f81
type: structure
