defaultPlacement: end
enableVersioning: true
handle: references
name: References
propagationMethod: all
siteSettings:
  1c00b42a-dae4-4f15-a772-533bb5b53e7c: # Lautissimi (DE)
    enabledByDefault: true
    hasUrls: true
    template: references/_entry
    uriFormat: references
type: single
